image: python:2.7.6
clone:
  depth: full
pipelines:
  branches:
    produkcijska:
      - step:
          script:
            - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git production:master