image: python:3.7.2
clone:
  depth: full
pipelines:
  branches:
    produkcijska:
      - step:
          script:
            - git push -f https://heroku:$HEROKU_API_KEY@https://git.heroku.com/$HEROKU_PRODUCTION.git production:master