image: python:2.7.16
clone:
  depth: full
pipelines:
  branches:
    produkcijska:
      - step:
          cache:
            - python
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION.git produkcijska:master
            